require:
  - rubocop-ordered_methods
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - standard

inherit_gem:
  rubocop-ordered_methods:
    - config/default.yml
  rubocop-performance:
    - config/default.yml
  rubocop-rails:
    - config/default.yml
  rubocop-rspec:
    - config/default.yml
  standard:
    - config/base.yml

AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/**/*
    - db/schema.rb
    - node_modules/**/*
    - old/**/*
    - script/**/*
    - vendor/**/*
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Rails/FilePath:
  EnforcedStyle: arguments

Rails/HelperInstanceVariable:
  Enabled: false # We memoize helpers using instance variables - that's okay

Rails/OutputSafety:
  Enabled: false # We use `html_safe` intentionally

Rails/RakeEnvironment:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false # We consciously use methods that skip validation - for a reason!

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/api/**/*
    - spec/features/**/*

RSpec/Dialect:
  Enabled: true
  PreferredMethods:
    context: describe

RSpec/ExampleLength:
  Max: 20
  Exclude:
    - spec/api/**/*
    - spec/controllers/**/*
    - spec/features/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/api/**/*
    - spec/controllers/**/*
    - spec/features/**/*
    - spec/mailers/**/*

RSpec/NamedSubject:
  Enabled: false # TODO: Re-enable once other lint issues in rspec are resolve. This is causing too much noise.

RSpec/VerifiedDoubles:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
