sudo: required
install: true

services:
  - docker

before_install:
  - sudo service postgresql stop # stop built-in postgres service, so the one in the db container can bind to port 5432 properly
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done # wait for postgresql to shutdown

script:
  - docker-compose up --exit-code-from test test

addons:
  code_climate:
    repo_token:
      secure: RRJer1xn1EIjov8dplpSO92f3pa5uTri8TBFZOEXLN15NRutopdWCjNSj82fnRfeqJRA35JvOu9XFr2EPQzdTPnNxELe7pQBKRf7E+D0r+ZPT8HJ82z+3CNfD7FNv0iD0Msx4feUdaDVDxjReW/uEKEDRBbJvpGMA6RO6r5355DgGcpSvBOrAyVMazId+FWTnDUfrwnFGgJkO8mXswqVjszIquUPo1hG47DCCdx6UMqgXTZZaSoSKtzqiZ10w16FFlfONMr7FtvE5gFIYObO5i02zALvyNwvFFo6IpKGo08QTNdGs0/0dP58ipqvg8BH28YCWpUaEhli9OXCoMr8BfeRcERfzlXzZdCrFAKR6VIFcWOPa0PluAfuxHXhhiSr0glnbwh/heQb2ov9cdMwGfzPCWpgb2hhLNSsn3SJctkangE8/4E+s84FLuttkM8V8hFEwD4ErOe0fprq+uZMqP4ZZpW40Iw8QShZR+a5ECWME9CxHgqrQWSsgnmMGx0OL1crVrEmox/vQz4HYBs3HduJXrBwNp0zJcZapoaUL9kQqWMoBySlXB6pJfubHAPYYwyMiHjVyQK9LHT7X4FgTEj9fMMdc4h/NI3jGQs3jlRHe7/BwzjPsbeb4E2OBbqvS9eE+yM0ZBrtEQhiAs8J+iN3TJhiaXD1i7fxBvCSzZI=
notifications:
  slack:
    secure: j60xEKuGEtPgyXWNgwGVfiVMq5HDESBmw/9BHujEkI6N6Bg7n61EuDTWmFd7F/aPylRiDekXmlPZg8QilWA9J2WVutKgRaylgk/dp/UDL/9y2C4NPBvcgE0pVIlmlxvBUsVIoo4kjYLZqSU39B4rbSvFlMeUT0BIW7xpUTh8iruQyV4dRQrZuE/X0H3lqJtlfMMNTNz1rd8KTB+1ucru2JWVePMTnqC6FgvbEuLgocu4lV6tRCVPosFaGvfZUTkE1xcQ7CXRuylGvuQVqS6mLI6rM7FstdLeI1cWqQ5vqLjz+8G0rJN+5sO3Z8bRezddk/bWelhh3MOmBM49yQmxzD2sQ+10u3+YJgLVJOA0E6WrhMDx0ZE+fq1BZTIMqVUQQzP0Jqrv8DyClwMlOi3oohrDYSZIJZqIiWdVOkxZOyRCZLWMthxjkRlq+4YMP/BLk2Q2RRcGmfFoVO6fL5HBLr1Tp6fC7G71kv9Iv+GYOlNuQ4Wl6vRv1zgTQ+T8ekdpJVxhmJLD6sEXmvf3fV4hi2Er2HkhzX1sifWJcZC1golcCh/y4BYqjucfLj7+3rq9+3/Mfo0+OZa3xS6tSdU69g/Se5dgbxDoZUxsoCFMLIvxc3ek8f2Ff+xcpaBA4A83+DtDNufnuldSe6rYUSRHY16r0ERyCmjZtaFe9msHjD4=
