# sudo: required
# install: true

language: shell
services:
  - docker

# before_install:
#   - sudo service postgresql stop # stop built-in postgres service, so the one in the db container can bind to port 5432 properly
#   - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done # wait for postgresql to shutdown

script:
  - docker-compose up --exit-code-from test test

notifications:
  slack:
    secure: j60xEKuGEtPgyXWNgwGVfiVMq5HDESBmw/9BHujEkI6N6Bg7n61EuDTWmFd7F/aPylRiDekXmlPZg8QilWA9J2WVutKgRaylgk/dp/UDL/9y2C4NPBvcgE0pVIlmlxvBUsVIoo4kjYLZqSU39B4rbSvFlMeUT0BIW7xpUTh8iruQyV4dRQrZuE/X0H3lqJtlfMMNTNz1rd8KTB+1ucru2JWVePMTnqC6FgvbEuLgocu4lV6tRCVPosFaGvfZUTkE1xcQ7CXRuylGvuQVqS6mLI6rM7FstdLeI1cWqQ5vqLjz+8G0rJN+5sO3Z8bRezddk/bWelhh3MOmBM49yQmxzD2sQ+10u3+YJgLVJOA0E6WrhMDx0ZE+fq1BZTIMqVUQQzP0Jqrv8DyClwMlOi3oohrDYSZIJZqIiWdVOkxZOyRCZLWMthxjkRlq+4YMP/BLk2Q2RRcGmfFoVO6fL5HBLr1Tp6fC7G71kv9Iv+GYOlNuQ4Wl6vRv1zgTQ+T8ekdpJVxhmJLD6sEXmvf3fV4hi2Er2HkhzX1sifWJcZC1golcCh/y4BYqjucfLj7+3rq9+3/Mfo0+OZa3xS6tSdU69g/Se5dgbxDoZUxsoCFMLIvxc3ek8f2Ff+xcpaBA4A83+DtDNufnuldSe6rYUSRHY16r0ERyCmjZtaFe9msHjD4=
