# NOTE: this is a work-in-progress. So far it can't start rails properly.
version: '3'
services:
  web:
    build: .
    ports: 
      - 3000:3000
    env_file: .env
    volumes:
      - .:/coyote
    command: bin/rails server thin -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
