version: "3"

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: coyote_development
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0.0-alpine3.16

  web: &rails
    build:
      args:
        bundle_without: "production"
        database_url: postgresql://postgres:postgres@db:5432/
        env: "development"
      context: .
    command: bundle exec rails server -b 0.0.0.0
    depends_on:
      - db
      - worker
    entrypoint: ./bin/docker_entrypoint
    environment:
      BOOTSNAP_CACHE_DIR: /bundle/bootsnap
      DATABASE_URL: postgresql://postgres:postgres@db:5432/
      HOST: http://web:3000/
      NODE_ENV: ${NODE_ENV:-development}
      RAILS_ENV: ${RAILS_ENV:-development}
      REDIS_URL: "redis://redis:6379/"
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEB_CONCURRENCY: 1
    ports:
      - 3000:3000
    stdin_open: true
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - .:/coyote:cached
      - bundle:/usr/local/bundle
      - node_modules:/coyote/node_modules
      - packs:/coyote/public/packs
      - rails_cache:/coyote/tmp/cache

  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444

  test:
    <<: *rails
    command: ./bin/ci
    depends_on:
      - db
      - selenium
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/coyote_test
      NODE_ENV: test
      PORT: 3030
      RAILS_ENV: test
      SECRET_KEY_BASE: 0c46014ccd12dae8ddf7094d53d2e0befb9580f8a81ac95ba0f3f735acba275fa4999ff9aeac421d26a0ca4207072f13dd0ba6d540cb39b8fccff341091d3e66
      SELENIUM_HOST: selenium:4444
      TEST_HOST: test
      WEB_CONCURRENCY: 1
    ports:
      - 3030:3030

  worker:
    <<: *rails
    command: bundle exec sidekiq
    depends_on:
      - redis
    ports: []

volumes:
  bundle:
  node_modules:
  packs:
  postgres:
  rails_cache:
  redis:
