version: '3'
services:
  web:
    build: .
    ports: 
      - 3000:3000
    env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:docker@db:5432/coyote_development
      COYOTE_DEV_DATABASE_URL: postgres://postgres:docker@db:5432/coyote_development
    volumes:
      - ./:/coyote
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
  test:
    build: .
    env_file: .env
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:docker@db:5432/coyote_test
      COYOTE_TEST_DATABASE_URL: postgres://postgres:docker@db:5432/coyote_development
    volumes:
      - ./:/coyote
    command: bundle exec rspec
    depends_on:
      - db
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
