test:
  service: Disk
  root: <%= Rails.root.join("tmp", "storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
aws:
  service: S3
  access_key_id: <%= Credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Credentials.dig(:aws, :secret_access_key) %>
  region: <%= Credentials.fetch(:aws, :region) { "us-east-1" } %>
  bucket: <%= Credentials.fetch(:aws, :bucket) { "teamcoyote-uploads-#{Rails.env}" } %>

# Use rails credentials:edit to set the Azure Storage secret (as azure:access_key)
azure:
  service: AzureStorage
  storage_account_name: <%= Credentials.dig(:azure, :account_name) %>
  storage_access_key: <%= Credentials.dig(:azure, :access_key) %>
  container: <%= Credentials.fetch(:azure, :container) { "teamcoyote-uploads-#{Rails.env}" } %>

# Use rails credentials:edit to set the GCS details (as google:bucket|project). Remember not to
# checkin your GCS keyfile to a repository!
google:
  service: GCS
  project: <%= Credentials.dig(:google, :project) %>
  credentials:
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    type: "service_account"
    client_email: <%= Credentials.dig(:google, :credentials, :client_email) %>
    client_id: <%= Credentials.dig(:google, :credentials, :client_id) %>
    client_x509_cert_url: <%= Credentials.dig(:google, :credentials, :client_x509_cert_url) %>
    private_key: <%= Credentials.dig(:google, :credentials, :private_key) %>
    private_key_id: <%= Credentials.dig(:google, :credentials, :private_key_id) %>
    project_id: <%= Credentials.dig(:google, :project %>
  bucket: <%= Credentials.fetch(:google, :bucket) { "teamcoyote-uploads-#{Rails.env}" } %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
